# Generated by Django 3.2 on 2021-04-16 17:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
    ]
